

ccflags-y += -I${ZEPHYR_BASE}/ext/lib/actions/private/lx_ble_app/include

ccflags-y += -I${ZEPHYR_BASE}/include/logging/

ccflags-y += -I${ZEPHYR_BASE}/samples/bt_box/src/include/

ccflags-y += -I${ZEPHYR_BASE}/samples/bt_box/src/main/lx_led_ctrl

obj-y += lx_fuction/lx_msg_deal.o
obj-y += lx_ble_init.o
