ccflags-y += -I${ZEPHYR_BASE}/samples/bt_box/src/include/
obj-$(CONFIG_RGB_LED_DEV) += light_rgb_core.o rgb_update_style.o light_rgb_tool.o light_rgb_viewmap.o
obj-$(CONFIG_RGB_LED_DEV) += light_rgb_giflib.o